"""base de datos con age incluido

Revision ID: 4a6ca6f9d57f
Revises: 577bb885de02
Create Date: 2015-05-22 15:32:48.865728

"""

# revision identifiers, used by Alembic.
revision = '4a6ca6f9d57f'
down_revision = '577bb885de02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'age')
    ### end Alembic commands ###
