"""base de datos inicial

Revision ID: 577bb885de02
Revises: None
Create Date: 2015-05-22 15:29:05.157706

"""

# revision identifiers, used by Alembic.
revision = '577bb885de02'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stp_id', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('username', sa.String(length=25, convert_unicode=True), nullable=True),
    sa.Column('name', sa.String(length=25, convert_unicode=True), nullable=True),
    sa.Column('lastname', sa.String(length=25, convert_unicode=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stp_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('group_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('name', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('lastname', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=255, convert_unicode=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('students')
    op.drop_table('group_sessions')
    op.drop_table('groups')
    op.drop_table('users')
    ### end Alembic commands ###
